### ISSUE TITLE
Server doesn´t start

### ISSUE THREAD

**Issue by Ice81** [LilaQ/MCC_Serve#7]
Hi everybody,
i try to start the MCC_Serve, but i get only this Error:
`# starting HTTP server (MCC & WebUI)
Task exception was never retrieved
future: <Task finished coro=<start_http() done, defined at mcc_server.py:77> exception=PermissionError(13, "error while attempting to bind on address ('0.0.0.0', 80): permission denied")>
Traceback (most recent call last):
  File "mcc_server.py", line 110, in start_http
    await http_site.start()
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
PermissionError: [Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied`

someone possibly also had this error and can help me?

in the appendix, my two config files
`import logging

LOGGING_LEVEL = logging.INFO # NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL

SERVER_LANGUAGE = "de"
SERVER_USE_HTTPS = False # True / False
SERVER_PORT_HTTPS = 8080
SERVER_PORT_HTTP = 80
SERVER_ADDRESS = "http://192.168.178.4/"
# in the format of: http://192.168.1.114/
#
# don't forget the trailing slash /

MQTT_ENABLED = 0
MQTT_SERVER_ADDRESS = ""
MQTT_SERVER_PORT = 0
MQTT_USER = ""
MQTT_PW = ""

#TELEGRAM BOT
TB_ENABLED = 0
TB_TOKEN = ""
TB_CHANNELID = 0
`
`{
        "server_address": "http://192.168.178.4/",
        "language": "de",
        "category_replacements" : [
                {
                        "source_categories" : [],
                        "target_category" : ""
                }
        ]
}
`

Thanks in advance for your help

**Comment by kovz** [comment]
I had the same issue. This means you already have some web server, which listening on port 80. To be sure, change port to 81 and try again. If it works - try find what kind of server is already running.
